name: Push to Docker Hub
on: [push]
env:
  DOCKER_TAG: 4armed/nginx:1-alpine-3.8

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_BUILD_PASSWORD }} | docker login -u ${{ secrets.DOCKER_BUILD_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build . -f Dockerfile --tag ${{ env.DOCKER_TAG }}
      - name: Push the tagged Docker image
        run: docker push ${{ env.DOCKER_TAG }}
